// Bakes the build-time VARIANT into a generated constant so runtime code
// (main.ts) knows which flavor it is, process.env is not available at runtime
// on StartOS. Run before tsc/ncc. Output is gitignored.
const fs = require('fs')
const path = require('path')

const variant = process.env.VARIANT === 'playerbots' ? 'playerbots' : 'vanilla'
const root = path.join(__dirname, '..')

const out = path.join(root, 'startos', 'variant.gen.ts')
fs.writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-variant.js, do not edit, do not commit.\n` +
    `export const BUILD_VARIANT: 'vanilla' | 'playerbots' = ${JSON.stringify(variant)}\n`,
)
console.log(`variant.gen.ts → ${variant}`)

// instructions.md is packed by start-cli from the repo root. Generate it from
// the variant template so each build ships the right docs. Generated +
// gitignored, like variant.gen.ts.
fs.copyFileSync(
  path.join(root, `instructions.${variant}.md`),
  path.join(root, 'instructions.md'),
)
console.log(`instructions.md → ${variant}`)
