// Bakes the build-time VARIANT into a generated constant so runtime code
// (main.ts) knows which flavor it is — process.env is not available at runtime
// on StartOS. Run before tsc/ncc. Output is gitignored.
const fs = require('fs')
const path = require('path')

const variant = process.env.VARIANT === 'playerbots' ? 'playerbots' : 'vanilla'
const out = path.join(__dirname, '..', 'startos', 'variant.gen.ts')
fs.writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/gen-variant.js — do not edit, do not commit.\n` +
    `export const BUILD_VARIANT: 'vanilla' | 'playerbots' = ${JSON.stringify(variant)}\n`,
)
console.log(`variant.gen.ts → ${variant}`)
